name: nnue
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2023.12.12
  - cudatoolkit=10.2.89
  - freetype=2.12.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lerc=3.0
  - libdeflate=1.17
  - libpng=1.6.39
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.13
  - pillow=10.2.0
  - pip=23.3.1
  - python=3.9.18
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tbb=2021.8.0
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - typing_extensions=4.9.0
  - tzdata=2024a
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cupy-cuda102==12.3.0
      - fastrlock==0.8.2
